config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'reports' => 'reports#index'
  post 'reports' => 'reports#download'
  get 'reports/export' => 'reports#download'

  # Entity reports require you to pick an entity in order to run a report
  get 'reports/entity/:entity'                       => 'reports#pick_entity'
  get 'reports/entity/:entity/:entity_id'            => 'reports#entity_reports'
  get 'reports/entity/:entity/:entity_id/:report_id' => 'reports#output_report'

  resources :patients do
    resources :acute_rehabs
    resources :annual_evaluations
    resources :omrs
  end

  resources :facilities

  root to: redirect('/patients')
end

app/views/layouts/_nav.html.slim
- if user_signed_in?
  nav#sci-nav.top-bar data-topbar="" role="navigation" 
    ul.title-area
      li.name
        h1
          a href="/" SCI Interim
      /! Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
      li.toggle-topbar.menu-icon
        a href="#" 
          span Menu
    section.top-bar-section
      /! Right Nav Section
      ul.right
        li
          a href="/" Registry
        li.active
          = link_to "Add New Patient", new_patient_path
        li
          = link_to 'Reports', reports_path
          li.has-dropdown
            a href="#"  #{current_user.email}
            ul.dropdown
              li
                = link_to 'Logout', destroy_user_session_path, :method => :delete 

app/views/layouts/_patientnav.html.slim
.top-bar#patient-nav
  .container
    .row
      ul.inline-list
        li
          ul
            li
              a href="#{edit_patient_path(@patient)}"
                .patient-name = "#{@patient.last_name}, #{@patient.first_name}" 
              .label.label-default
                = @patient.va_status
        li
          ul.list-container
            li 
              = @patient.gender
              |, 
              = @patient.computed_age 
              |   
              | years
            li
              | SSN: 
              = @patient.ssn  
            li 
              | DOB: 
              = localize(@patient.dob)
        li
          ul.panel.callout
            li
              strong SCI/D
            li
              = @patient.sci_type
              | ,  
              = @patient.is_on_active_duty
            / TODO: Add SCI Hub
            li
              | SCI Physician:
              |   
              = @patient.assigned_sci_hub_physician_first_name 
              |   
              = @patient.assigned_sci_hub_physician_last_name 
        li
          ul.list-container
            li
              strong Assigned VAMC: 
              = @patient.assigned_vamc
            li 
              strong VA PCP: 
              = @patient.va_facility_pcp_first_name   
              |   
              = @patient.va_facility_pcp_last_name

app/views/layouts/_patientnav_alternate.html.slim
.top-bar#alternate
  .container
    .row
      .medium-6.columns
        ul.inline-list.right
          li
            a href="#{edit_patient_path(@patient)}"
              .patient-name = "#{@patient.last_name}, #{@patient.first_name}" 
          li.label.label-default
            = @patient.va_status
      .medium-2.columns
        = link_to '+ Annual Evaluation', new_patient_annual_evaluation_path(@patient), { class: "button secondary expand" }
      .medium-2.columns
        = link_to '+ Acute Rehab', new_patient_acute_rehab_path(@patient), { class: "button secondary expand" }
      .medium-2.columns
        = link_to '+ OMR', new_patient_omr_path(@patient), { class: "button secondary expand" }


  

app/views/layouts/application.html.slim
doctype html
html
  head
    title SCI Interim
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .main-container
      = render partial: "layouts/nav"
      - if content_for?(:nav_patient) 
        = yield(:nav_patient)
      - else
        / Main
        .container
            .row
              .medium-12.columns
                p.text-warning.text-right
                  = notice
                p.text-error.text-right
                  = alert
            .row
              .medium-12.columns
                  = content_for?(:application_body) ? yield(:application_body) : yield

    javascript:

      // Todo: This should be cleaned up
      (function highlightActiveMenuItem() {
        var url = window.location.pathname;
        var exactMatch = $('ul.nav a[href="' + url + '"]');

        if (exactMatch[0]) {
          exactMatch.parent().addClass('active');
        } else {
          $('ul.nav a').filter(function () {
            return window.location.href.match(this.href);
          }).first().parent().addClass('active');
        }
      })();

      $('.detail-button').on('click', function(e) {
          e.preventDefault();
          var $this = $(this);
          var $collapse = $this.closest('.collapse-group').find('.collapse');
          $collapse.collapse('toggle');
      });

      jQuery(document).ready(function($) {
          $(".clickable-row").click(function() {
              window.document.location = $(this).data("href");
          });
      });

app/views/layouts/patient_edit.html.slim
- content_for :application_body do

- content_for :nav_patient do
  = render partial: "layouts/patientnav_alternate"  
  .container 
    .row
      .medium-12.columns
        == content_for?(:form) ? yield(:form) : yield
/       .medium-3.columns
/         table.table.table-bordered
/           tr
/             th Add a Patient Evaluation
/             tr.clickable
/               td = link_to '+ Annual Evaluation', new_patient_annual_evaluation_path(@patient), { class: "" }
/             tr.clickable
/               td = link_to '+ OMR', new_patient_omr_path(@patient), { class: "" }
/             tr.clickable
/               td = link_to '+ Acute Rehab', new_patient_acute_rehab_path(@patient), { class: "" }    
/         table.table.table-bordered.table-striped
/           tr
/             th Episodes of Care History
/           - for episode in @patient.episode_of_cares do
/             tr class="clickable-row" data-href=edit_polymorphic_url([@patient, episode])
/               .medium-12.columns
/                 td 
/                   = episode.class.name 
/                   small.right
/                     |   
/                     = episode.episode_date
/           - if @patient.episode_of_cares.empty?
/             tr
/               td There are no recorded episodes of care for this patient  

= render template: "layouts/application"